### ISSUE TITLE
Wrong location when running with NUnit

### ISSUE THREAD

**Issue by afish** [MarcelGosselin/LpSolveDotNet#4]
Hi.
Snippet
`Assembly.GetExecutingAssembly().Location`
returns incorrect path when binary is used in NUnit unit tests, something like
`C:\\Users\\user\\AppData\\Local\\Temp\\b420crko.0lq\\bbczl1ms.bv4\\Tests\\assembly\\dl3\\dcbc711f\\bc4eb68b_98f7d101\\Tests.dll`
Changing this to
`new Uri(Assembly.GetExecutingAssembly().CodeBase).LocalPath`
should fix the problem.

**Comment by MarcelGosselin** [comment]
@afish I just came back from vacation so I started looking at this yesterday night. It took me a lot of time to reproduce the error (I went to bed at 2AM). I will fix it by the end of the week and package a new version.

**Comment by MarcelGosselin** [comment]
Fixed in version 4.0
