### ISSUE TITLE
Detecting x64 should not be based on pointer size

### ISSUE THREAD

**Issue by afish** [MarcelGosselin/LpSolveDotNet#5]
Detecting architecture should not be based on pointer size, it is probably better to use `System.Environment.Is64BitProcess` to detect x64 architecture.

**Comment by MarcelGosselin** [comment]
You are right, however currently the library can run on .NET 2.0 and [Environment.Is64BitProcess](https://msdn.microsoft.com/en-us/library/system.environment.is64bitprocess.aspx) has been introduced in 4.0.
I will not change the target framework for now if this is the only requirement.
